image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-vscode.cmake-tools@1.4.2:85XiRZZTNCh6JgvEqefqww==
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
    - cschlosser.doxdocgen@0.5.2:SsSNhKMGwp5iVRhI1fnHVA==
